### ISSUE TITLE
Can't use docker network references when building client-side code 

### ISSUE THREAD

**Issue by dcalacci** [rifflearning/riff-docker#1]
We're almost at the point where we can deploy to a public AWS cloudformation stack, but one issue is with network references when we deploy. 

Using `swarm.py deploy -f production.yml` as it stands now deploys all resources to a cloudformation stack correctly, except that the client-side riff-rtc code tries to make requests using the `riff-server` reference from our docker-compose config, and we get the following error:

```
Firefox can’t establish a connection to the server at ws://riff-server:3000/socket.io/?EIO=3&transport=websocket.
websocket.js:112
```

I think this is because `riff-server` isn't getting expanded / client isn't in the right namespace (not on the docker VPC). It's a little weird because when I use the same `production.yml` locally and deploy to a local swarm, it works fine.

In `production.yml`, our config for `riff-rtc` looks like:
```
  riff-rtc:
    image: 127.0.0.1:5000/riff-rtc
    build:
      context: https://github.com/rifflearning/riff-rtc.git#docker
      args:
        NODE_ENV: "production"
        REACT_APP_SERVER_TOKEN: "my-secret"
        REACT_APP_SERVER_URL: http://riff-server:3000
```

The problem is that when we deploy, `REACT_APP_SERVER_URL` doesn't get populated with the right URL; the variable stays as `http://riff-server:3000` on the react build and that's the request that the client makes.

We should be able to have the client point to a public DNS of the cloudformation deployment for these requests on a deployment

Not sure how to fix this as of yet
